# Generated by Django 5.0.6 on 2024-05-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('skill1', models.CharField(max_length=100)),
                ('skill2', models.CharField(max_length=100)),
                ('skill3', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.IntegerField()),
                ('education_course', models.CharField(max_length=100)),
                ('education_school', models.CharField(max_length=100)),
                ('education_start_date', models.DateField()),
                ('education_end_date', models.DateField()),
                ('certificate_course', models.CharField(max_length=100)),
                ('certificate_school', models.CharField(max_length=150)),
                ('certificate_images', models.ImageField(upload_to='')),
                ('project_name', models.CharField(max_length=150)),
                ('project_summary', models.TextField()),
                ('project_link', models.URLField()),
                ('project_image', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
    ]
